import { 
  faGlobe, faChartLine, faBook, faLightbulb, faChartBar, faArrowRight, faUser, faEnvelope, faBell, faHeart, faStar, faCheck, faTimes, faSearch, faHome, faCog, faLock, faDownload, faUpload, faEdit, faTrash, faPlus, faMinus, faInfoCircle, faExclamationTriangle, faQuestionCircle, faCalendar, faCamera, faImage, faLink, faPaperclip, faPhone, faPrint, faShare, faShoppingCart, faSignOutAlt, faSync, faThumbsUp, faThumbsDown, faUserCircle, faUsers, faWallet, faWifi, faWrench
} from '@fortawesome/free-solid-svg-icons';
import { faSmile, faFile, faFolder, faClock, faComment, faCopy, faEye, faEyeSlash, faFlag, faHandPaper, faKeyboard, faLightbulb as faLightbulbRegular, faStar as faStarRegular } from '@fortawesome/free-regular-svg-icons';
import { faTwitter, faFacebookF, faLinkedinIn, faGithub, faGoogle, faInstagram, faYoutube, faDribbble, faBehance, faSlack, faTwitch, faWhatsapp, faDiscord } from '@fortawesome/free-brands-svg-icons';

export const allFontAwesomeIcons = [
  // Solid
  { icon: faGlobe, name: 'faGlobe', prefix: 'fas' },
  { icon: faChartLine, name: 'faChartLine', prefix: 'fas' },
  { icon: faBook, name: 'faBook', prefix: 'fas' },
  { icon: faLightbulb, name: 'faLightbulb', prefix: 'fas' },
  { icon: faChartBar, name: 'faChartBar', prefix: 'fas' },
  { icon: faArrowRight, name: 'faArrowRight', prefix: 'fas' },
  { icon: faUser, name: 'faUser', prefix: 'fas' },
  { icon: faEnvelope, name: 'faEnvelope', prefix: 'fas' },
  { icon: faBell, name: 'faBell', prefix: 'fas' },
  { icon: faHeart, name: 'faHeart', prefix: 'fas' },
  { icon: faStar, name: 'faStar', prefix: 'fas' },
  { icon: faCheck, name: 'faCheck', prefix: 'fas' },
  { icon: faTimes, name: 'faTimes', prefix: 'fas' },
  { icon: faSearch, name: 'faSearch', prefix: 'fas' },
  { icon: faHome, name: 'faHome', prefix: 'fas' },
  { icon: faCog, name: 'faCog', prefix: 'fas' },
  { icon: faLock, name: 'faLock', prefix: 'fas' },
  { icon: faDownload, name: 'faDownload', prefix: 'fas' },
  { icon: faUpload, name: 'faUpload', prefix: 'fas' },
  { icon: faEdit, name: 'faEdit', prefix: 'fas' },
  { icon: faTrash, name: 'faTrash', prefix: 'fas' },
  { icon: faPlus, name: 'faPlus', prefix: 'fas' },
  { icon: faMinus, name: 'faMinus', prefix: 'fas' },
  { icon: faInfoCircle, name: 'faInfoCircle', prefix: 'fas' },
  { icon: faExclamationTriangle, name: 'faExclamationTriangle', prefix: 'fas' },
  { icon: faQuestionCircle, name: 'faQuestionCircle', prefix: 'fas' },
  { icon: faCalendar, name: 'faCalendar', prefix: 'fas' },
  { icon: faCamera, name: 'faCamera', prefix: 'fas' },
  { icon: faImage, name: 'faImage', prefix: 'fas' },
  { icon: faLink, name: 'faLink', prefix: 'fas' },
  { icon: faPaperclip, name: 'faPaperclip', prefix: 'fas' },
  { icon: faPhone, name: 'faPhone', prefix: 'fas' },
  { icon: faPrint, name: 'faPrint', prefix: 'fas' },
  { icon: faShare, name: 'faShare', prefix: 'fas' },
  { icon: faShoppingCart, name: 'faShoppingCart', prefix: 'fas' },
  { icon: faSignOutAlt, name: 'faSignOutAlt', prefix: 'fas' },
  { icon: faSync, name: 'faSync', prefix: 'fas' },
  { icon: faThumbsUp, name: 'faThumbsUp', prefix: 'fas' },
  { icon: faThumbsDown, name: 'faThumbsDown', prefix: 'fas' },
  { icon: faUserCircle, name: 'faUserCircle', prefix: 'fas' },
  { icon: faUsers, name: 'faUsers', prefix: 'fas' },
  { icon: faWallet, name: 'faWallet', prefix: 'fas' },
  { icon: faWifi, name: 'faWifi', prefix: 'fas' },
  { icon: faWrench, name: 'faWrench', prefix: 'fas' },
  // Regular
  { icon: faSmile, name: 'faSmile', prefix: 'far' },
  { icon: faFile, name: 'faFile', prefix: 'far' },
  { icon: faFolder, name: 'faFolder', prefix: 'far' },
  { icon: faClock, name: 'faClock', prefix: 'far' },
  { icon: faComment, name: 'faComment', prefix: 'far' },
  { icon: faCopy, name: 'faCopy', prefix: 'far' },
  { icon: faEye, name: 'faEye', prefix: 'far' },
  { icon: faEyeSlash, name: 'faEyeSlash', prefix: 'far' },
  { icon: faFlag, name: 'faFlag', prefix: 'far' },
  { icon: faHandPaper, name: 'faHandPaper', prefix: 'far' },
  { icon: faKeyboard, name: 'faKeyboard', prefix: 'far' },
  { icon: faLightbulbRegular, name: 'faLightbulb', prefix: 'far' },
  { icon: faStarRegular, name: 'faStar', prefix: 'far' },
  // Brands
  { icon: faTwitter, name: 'faTwitter', prefix: 'fab' },
  { icon: faFacebookF, name: 'faFacebookF', prefix: 'fab' },
  { icon: faLinkedinIn, name: 'faLinkedinIn', prefix: 'fab' },
  { icon: faGithub, name: 'faGithub', prefix: 'fab' },
  { icon: faGoogle, name: 'faGoogle', prefix: 'fab' },
  { icon: faInstagram, name: 'faInstagram', prefix: 'fab' },
  { icon: faYoutube, name: 'faYoutube', prefix: 'fab' },
  { icon: faDribbble, name: 'faDribbble', prefix: 'fab' },
  { icon: faBehance, name: 'faBehance', prefix: 'fab' },
  { icon: faSlack, name: 'faSlack', prefix: 'fab' },
  { icon: faTwitch, name: 'faTwitch', prefix: 'fab' },
  { icon: faWhatsapp, name: 'faWhatsapp', prefix: 'fab' },
  { icon: faDiscord, name: 'faDiscord', prefix: 'fab' },
]; 