import type { NextApiRequest, NextApiResponse } from 'next';
import dbConnect from '../../../lib/mongodb';
import User from '../../../models/User';
import EmailTemplate from '../../../models/EmailTemplate';

const premiumTemplates = [
  {
    name: 'Market Volatility Alert',
    subject: 'Market Alert: {{alertType}} - Action Required',
    htmlContent: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #FF6B2C 0%, #FF8A50 100%); padding: 30px 20px; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 28px; font-weight: 700;">⚠️ MARKET ALERT</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0; font-size: 16px;">{{alertType}} Detected</p>
        </div>
        
        <!-- Alert Box -->
        <div style="background: #FFF3E0; border-left: 5px solid #FF6B2C; margin: 0; padding: 25px;">
          <h2 style="color: #E65100; margin: 0 0 15px 0; font-size: 20px;">Immediate Attention Required</h2>
          <p style="color: #333; line-height: 1.6; margin: 0; font-size: 16px;">
            <strong>{{userName}}</strong>, we've detected significant market movements that may impact your portfolio. 
            Our AI analysis suggests <strong>{{recommendation}}</strong>.
          </p>
        </div>
        
        <!-- Market Data -->
        <div style="padding: 30px 20px; background: #f8f9fa;">
          <div style="display: flex; justify-content: space-between; margin-bottom: 20px; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
            <div style="text-align: center; flex: 1;">
              <div style="color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 5px;">S&P 500</div>
              <div style="font-size: 24px; font-weight: bold; color: {{sp500Color}};">{{sp500Change}}</div>
            </div>
            <div style="text-align: center; flex: 1;">
              <div style="color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 5px;">NASDAQ</div>
              <div style="font-size: 24px; font-weight: bold; color: {{nasdaqColor}};">{{nasdaqChange}}</div>
            </div>
            <div style="text-align: center; flex: 1;">
              <div style="color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 5px;">VIX</div>
              <div style="font-size: 24px; font-weight: bold; color: {{vixColor}};">{{vixLevel}}</div>
            </div>
          </div>
          
          <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <h3 style="color: #333; margin: 0 0 15px 0; font-size: 18px;">Recommended Actions:</h3>
            <ul style="color: #555; line-height: 1.8; margin: 0; padding-left: 20px;">
              <li>{{action1}}</li>
              <li>{{action2}}</li>
              <li>{{action3}}</li>
            </ul>
          </div>
        </div>
        
        <!-- CTA -->
        <div style="text-align: center; padding: 30px 20px; background: #f8f9fa;">
          <a href="{{portfolioUrl}}" style="background: linear-gradient(135deg, #FF6B2C 0%, #FF8A50 100%); color: white; padding: 15px 40px; text-decoration: none; border-radius: 30px; font-weight: bold; font-size: 16px; display: inline-block; box-shadow: 0 4px 15px rgba(255, 107, 44, 0.3);">
            Review Your Portfolio →
          </a>
          <p style="color: #666; margin: 20px 0 0 0; font-size: 14px;">Or call our advisors at <strong>{{phoneNumber}}</strong></p>
        </div>
        
        <!-- Footer -->
        <div style="background: #333; color: white; padding: 25px 20px; text-align: center;">
          <p style="margin: 0 0 10px 0; font-size: 14px;">This alert was generated by IncomeGrow AI at {{timestamp}}</p>
          <p style="margin: 0; font-size: 12px; color: #ccc;">© 2024 IncomeGrow Financial. Market data delayed by 15 minutes.</p>
        </div>
      </div>
    `,
    textContent: 'MARKET ALERT: {{alertType}}. {{userName}}, significant market movements detected. Recommendation: {{recommendation}}. S&P 500: {{sp500Change}}, NASDAQ: {{nasdaqChange}}, VIX: {{vixLevel}}. Actions: {{action1}}, {{action2}}, {{action3}}. Review portfolio: {{portfolioUrl}}',
    variables: ['userName', 'alertType', 'recommendation', 'sp500Change', 'sp500Color', 'nasdaqChange', 'nasdaqColor', 'vixLevel', 'vixColor', 'action1', 'action2', 'action3', 'portfolioUrl', 'phoneNumber', 'timestamp'],
    category: 'notification',
  },
  {
    name: 'Monthly Portfolio Report',
    subject: '📊 Your {{month}} Portfolio Performance Report',
    htmlContent: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 650px; margin: 0 auto; background: #ffffff;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); padding: 40px 20px; text-align: center; position: relative;">
          <div style="background: rgba(255,255,255,0.1); border-radius: 50%; width: 80px; height: 80px; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center;">
            <span style="font-size: 36px;">📊</span>
          </div>
          <h1 style="color: white; margin: 0; font-size: 32px; font-weight: 300; letter-spacing: -1px;">Portfolio Report</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 10px 0 0 0; font-size: 18px;">{{month}} Performance Summary</p>
        </div>
        
        <!-- Performance Summary -->
        <div style="padding: 40px 30px; background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);">
          <div style="text-align: center; margin-bottom: 30px;">
            <h2 style="color: #333; margin: 0 0 10px 0; font-size: 24px; font-weight: 600;">Hello {{userName}}!</h2>
            <p style="color: #666; margin: 0; font-size: 16px; line-height: 1.5;">Here's how your investments performed this month</p>
          </div>
          
          <!-- Key Metrics -->
          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px;">
            <div style="background: white; padding: 25px; border-radius: 12px; text-align: center; box-shadow: 0 4px 20px rgba(0,0,0,0.08);">
              <div style="color: #2ECC71; font-size: 36px; font-weight: bold; margin-bottom: 5px;">{{totalReturn}}</div>
              <div style="color: #666; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">Total Return</div>
            </div>
            <div style="background: white; padding: 25px; border-radius: 12px; text-align: center; box-shadow: 0 4px 20px rgba(0,0,0,0.08);">
              <div style="color: #3498DB; font-size: 36px; font-weight: bold; margin-bottom: 5px;">{{portfolioValue}}</div>
              <div style="color: #666; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">Portfolio Value</div>
            </div>
            <div style="background: white; padding: 25px; border-radius: 12px; text-align: center; box-shadow: 0 4px 20px rgba(0,0,0,0.08);">
              <div style="color: {{monthlyChangeColor}}; font-size: 36px; font-weight: bold; margin-bottom: 5px;">{{monthlyChange}}</div>
              <div style="color: #666; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">Monthly Change</div>
            </div>
          </div>
        </div>
        
        <!-- Asset Allocation -->
        <div style="padding: 40px 30px; background: white;">
          <h3 style="color: #333; margin: 0 0 25px 0; font-size: 22px; font-weight: 600; text-align: center;">Asset Allocation</h3>
          <div style="background: #f8f9ff; padding: 25px; border-radius: 12px; margin-bottom: 25px;">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px; align-items: center;">
              <span style="color: #333; font-weight: 600;">📈 Stocks</span>
              <div style="display: flex; align-items: center;">
                <div style="width: 120px; height: 8px; background: #e0e0e0; border-radius: 4px; margin-right: 10px;">
                  <div style="width: {{stocksPercent}}%; height: 100%; background: linear-gradient(90deg, #4CAF50, #8BC34A); border-radius: 4px;"></div>
                </div>
                <span style="color: #333; font-weight: bold; min-width: 40px;">{{stocksPercent}}%</span>
              </div>
            </div>
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px; align-items: center;">
              <span style="color: #333; font-weight: 600;">🏛️ Bonds</span>
              <div style="display: flex; align-items: center;">
                <div style="width: 120px; height: 8px; background: #e0e0e0; border-radius: 4px; margin-right: 10px;">
                  <div style="width: {{bondsPercent}}%; height: 100%; background: linear-gradient(90deg, #2196F3, #03A9F4); border-radius: 4px;"></div>
                </div>
                <span style="color: #333; font-weight: bold; min-width: 40px;">{{bondsPercent}}%</span>
              </div>
            </div>
            <div style="display: flex; justify-content: space-between; align-items: center;">
              <span style="color: #333; font-weight: 600;">💰 Cash</span>
              <div style="display: flex; align-items: center;">
                <div style="width: 120px; height: 8px; background: #e0e0e0; border-radius: 4px; margin-right: 10px;">
                  <div style="width: {{cashPercent}}%; height: 100%; background: linear-gradient(90deg, #FFC107, #FF9800); border-radius: 4px;"></div>
                </div>
                <span style="color: #333; font-weight: bold; min-width: 40px;">{{cashPercent}}%</span>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Insights -->
        <div style="padding: 40px 30px; background: #f8f9fa;">
          <h3 style="color: #333; margin: 0 0 20px 0; font-size: 22px; font-weight: 600;">💡 Key Insights</h3>
          <div style="background: white; padding: 25px; border-radius: 12px; border-left: 5px solid #FF6B2C;">
            <p style="color: #555; line-height: 1.7; margin: 0 0 15px 0; font-size: 16px;">{{insight1}}</p>
            <p style="color: #555; line-height: 1.7; margin: 0 0 15px 0; font-size: 16px;">{{insight2}}</p>
            <p style="color: #555; line-height: 1.7; margin: 0; font-size: 16px;">{{insight3}}</p>
          </div>
        </div>
        
        <!-- CTA -->
        <div style="text-align: center; padding: 40px 30px; background: white;">
          <h3 style="color: #333; margin: 0 0 20px 0; font-size: 20px;">Ready to optimize your portfolio?</h3>
          <a href="{{optimizeUrl}}" style="background: linear-gradient(135deg, #FF6B2C 0%, #FF8A50 100%); color: white; padding: 15px 35px; text-decoration: none; border-radius: 30px; font-weight: bold; font-size: 16px; display: inline-block; margin-right: 15px; box-shadow: 0 4px 15px rgba(255, 107, 44, 0.3);">
            Optimize Portfolio
          </a>
          <a href="{{fullReportUrl}}" style="background: transparent; color: #FF6B2C; padding: 15px 35px; text-decoration: none; border: 2px solid #FF6B2C; border-radius: 30px; font-weight: bold; font-size: 16px; display: inline-block;">
            View Full Report
          </a>
        </div>
        
        <!-- Footer -->
        <div style="background: #333; color: white; padding: 30px; text-align: center;">
          <p style="margin: 0 0 10px 0; font-size: 14px;">Questions? Reply to this email or call {{supportPhone}}</p>
          <p style="margin: 0; font-size: 12px; color: #ccc;">© 2024 IncomeGrow Financial | Investment Advisory Services</p>
        </div>
      </div>
    `,
    textContent: 'Portfolio Report for {{month}}. Hello {{userName}}, Total Return: {{totalReturn}}, Portfolio Value: {{portfolioValue}}, Monthly Change: {{monthlyChange}}. Asset Allocation - Stocks: {{stocksPercent}}%, Bonds: {{bondsPercent}}%, Cash: {{cashPercent}}%. Key Insights: {{insight1}}, {{insight2}}, {{insight3}}. Optimize: {{optimizeUrl}}',
    variables: ['userName', 'month', 'totalReturn', 'portfolioValue', 'monthlyChange', 'monthlyChangeColor', 'stocksPercent', 'bondsPercent', 'cashPercent', 'insight1', 'insight2', 'insight3', 'optimizeUrl', 'fullReportUrl', 'supportPhone'],
    category: 'marketing',
  },
  {
    name: 'Investment Opportunity',
    subject: '🎯 Exclusive Investment Opportunity - {{opportunityName}}',
    htmlContent: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 20px; text-align: center; position: relative; overflow: hidden;">
          <div style="position: absolute; top: -50px; right: -50px; width: 100px; height: 100px; background: rgba(255,255,255,0.1); border-radius: 50%;"></div>
          <div style="position: absolute; bottom: -30px; left: -30px; width: 60px; height: 60px; background: rgba(255,255,255,0.1); border-radius: 50%;"></div>
          <h1 style="color: white; margin: 0; font-size: 28px; font-weight: 700; position: relative; z-index: 2;">🎯 EXCLUSIVE OPPORTUNITY</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0; font-size: 16px; position: relative; z-index: 2;">Limited Time Investment</p>
        </div>
        
        <!-- Opportunity Details -->
        <div style="padding: 40px 30px; background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; text-align: center;">
          <h2 style="margin: 0 0 15px 0; font-size: 32px; font-weight: 300; text-shadow: 0 2px 4px rgba(0,0,0,0.3);">{{opportunityName}}</h2>
          <div style="background: rgba(255,255,255,0.2); padding: 20px; border-radius: 12px; backdrop-filter: blur(10px);">
            <div style="font-size: 18px; margin-bottom: 10px;">Expected Return</div>
            <div style="font-size: 48px; font-weight: bold; margin-bottom: 5px;">{{expectedReturn}}</div>
            <div style="font-size: 14px; opacity: 0.9;">{{timeframe}} Investment Period</div>
          </div>
        </div>
        
        <!-- Key Features */}
        <div style="padding: 40px 30px; background: white;">
          <h3 style="color: #333; margin: 0 0 30px 0; font-size: 24px; font-weight: 600; text-align: center;">Why This Opportunity?</h3>
          <div style="display: grid; gap: 20px;">
            <div style="display: flex; align-items: flex-start; padding: 20px; background: #f8f9ff; border-radius: 12px; border-left: 4px solid #667eea;">
              <div style="background: #667eea; color: white; width: 30px; height: 30px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 15px; flex-shrink: 0; font-weight: bold;">1</div>
              <div>
                <h4 style="color: #333; margin: 0 0 8px 0; font-size: 18px; font-weight: 600;">{{feature1Title}}</h4>
                <p style="color: #666; margin: 0; line-height: 1.6;">{{feature1Description}}</p>
              </div>
            </div>
            <div style="display: flex; align-items: flex-start; padding: 20px; background: #f0fff4; border-radius: 12px; border-left: 4px solid #28a745;">
              <div style="background: #28a745; color: white; width: 30px; height: 30px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 15px; flex-shrink: 0; font-weight: bold;">2</div>
              <div>
                <h4 style="color: #333; margin: 0 0 8px 0; font-size: 18px; font-weight: 600;">{{feature2Title}}</h4>
                <p style="color: #666; margin: 0; line-height: 1.6;">{{feature2Description}}</p>
              </div>
            </div>
            <div style="display: flex; align-items: flex-start; padding: 20px; background: #fff8f0; border-radius: 12px; border-left: 4px solid #ffc107;">
              <div style="background: #ffc107; color: white; width: 30px; height: 30px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 15px; flex-shrink: 0; font-weight: bold;">3</div>
              <div>
                <h4 style="color: #333; margin: 0 0 8px 0; font-size: 18px; font-weight: 600;">{{feature3Title}}</h4>
                <p style="color: #666; margin: 0; line-height: 1.6;">{{feature3Description}}</p>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Risk & Minimum -->
        <div style="padding: 30px; background: #f8f9fa;">
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
            <div style="background: white; padding: 25px; border-radius: 12px; text-align: center; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">
              <div style="color: #dc3545; font-size: 16px; font-weight: 600; margin-bottom: 8px;">Risk Level</div>
              <div style="color: #333; font-size: 24px; font-weight: bold;">{{riskLevel}}</div>
            </div>
            <div style="background: white; padding: 25px; border-radius: 12px; text-align: center; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">
              <div style="color: #28a745; font-size: 16px; font-weight: 600; margin-bottom: 8px;">Minimum Investment</div>
              <div style="color: #333; font-size: 24px; font-weight: bold;">{{minimumInvestment}}</div>
            </div>
          </div>
        </div>
        
        <!-- Urgency & CTA -->
        <div style="padding: 40px 30px; background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%); text-align: center;">
          <div style="background: rgba(255,255,255,0.9); padding: 25px; border-radius: 15px; margin-bottom: 25px;">
            <h3 style="color: #d63384; margin: 0 0 10px 0; font-size: 20px;">⏰ Limited Time Offer</h3>
            <p style="color: #666; margin: 0; font-size: 16px; line-height: 1.5;">
              Only <strong>{{spotsLeft}} spots remaining</strong> • Deadline: <strong>{{deadline}}</strong>
            </p>
          </div>
          <a href="{{investUrl}}" style="background: linear-gradient(135deg, #FF6B2C 0%, #FF8A50 100%); color: white; padding: 18px 40px; text-decoration: none; border-radius: 30px; font-weight: bold; font-size: 18px; display: inline-block; box-shadow: 0 6px 20px rgba(255, 107, 44, 0.4); margin-bottom: 15px;">
            Invest Now →
          </a>
          <div>
            <a href="{{prospectusUrl}}" style="color: #666; text-decoration: none; font-size: 14px; border-bottom: 1px solid #666;">
              View Full Prospectus
            </a>
          </div>
        </div>
        
        <!-- Footer -->
        <div style="background: #2c3e50; color: white; padding: 30px; text-align: center;">
          <p style="margin: 0 0 15px 0; font-size: 14px; line-height: 1.6;">
            <strong>Disclaimer:</strong> All investments carry risk. Past performance doesn't guarantee future results. 
            Please consult with our advisors before investing.
          </p>
          <p style="margin: 0; font-size: 12px; color: #bdc3c7;">© 2024 IncomeGrow Financial | SEC Registered Investment Advisor</p>
        </div>
      </div>
    `,
    textContent: 'EXCLUSIVE INVESTMENT OPPORTUNITY: {{opportunityName}}. Expected Return: {{expectedReturn}} over {{timeframe}}. Features: {{feature1Title}}, {{feature2Title}}, {{feature3Title}}. Risk Level: {{riskLevel}}, Minimum: {{minimumInvestment}}. {{spotsLeft}} spots left, deadline {{deadline}}. Invest: {{investUrl}}',
    variables: ['opportunityName', 'expectedReturn', 'timeframe', 'feature1Title', 'feature1Description', 'feature2Title', 'feature2Description', 'feature3Title', 'feature3Description', 'riskLevel', 'minimumInvestment', 'spotsLeft', 'deadline', 'investUrl', 'prospectusUrl'],
    category: 'marketing',
  },
  {
    name: 'Account Security Alert',
    subject: '🔐 Security Alert: {{alertType}} - {{userName}}',
    htmlContent: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #e74c3c 0%, #c0392b 100%); padding: 30px 20px; text-align: center;">
          <div style="background: rgba(255,255,255,0.2); border-radius: 50%; width: 70px; height: 70px; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center;">
            <span style="font-size: 32px;">🔐</span>
          </div>
          <h1 style="color: white; margin: 0; font-size: 26px; font-weight: 700;">SECURITY ALERT</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0; font-size: 16px;">Account Protection Activated</p>
        </div>
        
        <!-- Alert Details -->
        <div style="background: #fff5f5; border-left: 5px solid #e74c3c; padding: 30px; margin: 0;">
          <h2 style="color: #c53030; margin: 0 0 15px 0; font-size: 20px; display: flex; align-items: center;">
            <span style="margin-right: 10px;">⚠️</span>
            {{alertType}} Detected
          </h2>
          <p style="color: #333; line-height: 1.6; margin: 0 0 20px 0; font-size: 16px;">
            <strong>Hello {{userName}},</strong><br><br>
            We detected {{alertDescription}} on your IncomeGrow Financial account. This alert was triggered to protect your financial assets.
          </p>
          <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #fed7d7;">
            <h3 style="color: #c53030; margin: 0 0 15px 0; font-size: 16px;">Incident Details:</h3>
            <table style="width: 100%; font-size: 14px; color: #555;">
              <tr>
                <td style="padding: 5px 0; font-weight: 600;">Time:</td>
                <td style="padding: 5px 0;">{{incidentTime}}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; font-weight: 600;">Location:</td>
                <td style="padding: 5px 0;">{{location}}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; font-weight: 600;">Device:</td>
                <td style="padding: 5px 0;">{{deviceInfo}}</td>
              </tr>
              <tr>
                <td style="padding: 5px 0; font-weight: 600;">IP Address:</td>
                <td style="padding: 5px 0; font-family: monospace;">{{ipAddress}}</td>
              </tr>
            </table>
          </div>
        </div>
        
        <!-- Action Required -->
        <div style="padding: 30px; background: white;">
          <h3 style="color: #333; margin: 0 0 20px 0; font-size: 20px; text-align: center;">🛡️ Immediate Action Required</h3>
          <div style="background: #f7fafc; padding: 25px; border-radius: 12px; margin-bottom: 25px;">
            <h4 style="color: #2d3748; margin: 0 0 15px 0; font-size: 16px;">If this was you:</h4>
            <ul style="color: #4a5568; line-height: 1.7; margin: 0 0 20px 0; padding-left: 20px;">
              <li>No further action needed - your account is secure</li>
              <li>Consider enabling 2FA for additional security</li>
              <li>Review your recent account activity</li>
            </ul>
            <div style="text-align: center;">
              <a href="{{confirmUrl}}" style="background: #48bb78; color: white; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: 600; display: inline-block;">
                ✓ This Was Me
              </a>
            </div>
          </div>
          
          <div style="background: #fff5f5; padding: 25px; border-radius: 12px; border: 1px solid #fed7d7;">
            <h4 style="color: #c53030; margin: 0 0 15px 0; font-size: 16px;">If this was NOT you:</h4>
            <ul style="color: #4a5568; line-height: 1.7; margin: 0 0 20px 0; padding-left: 20px;">
              <li><strong>Secure your account immediately</strong> - Change your password</li>
              <li>Review all recent transactions and activities</li>
              <li>Enable two-factor authentication</li>
              <li>Contact our security team immediately</li>
            </ul>
            <div style="text-align: center;">
              <a href="{{secureAccountUrl}}" style="background: #e53e3e; color: white; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: 600; display: inline-block; margin-right: 10px;">
                🔒 Secure My Account
              </a>
              <a href="tel:{{emergencyPhone}}" style="background: #d69e2e; color: white; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: 600; display: inline-block;">
                📞 Call Security
              </a>
            </div>
          </div>
        </div>
        
        <!-- Security Tips -->
        <div style="padding: 30px; background: #f8f9fa;">
          <h3 style="color: #333; margin: 0 0 20px 0; font-size: 18px; text-align: center;">🛡️ Security Best Practices</h3>
          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px;">
            <div style="background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
              <h4 style="color: #2b6cb0; margin: 0 0 10px 0; font-size: 14px; display: flex; align-items: center;">
                <span style="margin-right: 8px;">🔑</span>Strong Passwords
              </h4>
              <p style="color: #555; margin: 0; font-size: 13px; line-height: 1.5;">Use unique, complex passwords for all your accounts</p>
            </div>
            <div style="background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
              <h4 style="color: #2b6cb0; margin: 0 0 10px 0; font-size: 14px; display: flex; align-items: center;">
                <span style="margin-right: 8px;">📱</span>Enable 2FA
              </h4>
              <p style="color: #555; margin: 0; font-size: 13px; line-height: 1.5;">Add an extra layer of security to your account</p>
            </div>
            <div style="background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
              <h4 style="color: #2b6cb0; margin: 0 0 10px 0; font-size: 14px; display: flex; align-items: center;">
                <span style="margin-right: 8px;">👀</span>Monitor Activity
              </h4>
              <p style="color: #555; margin: 0; font-size: 13px; line-height: 1.5;">Regularly check your account for unusual activity</p>
            </div>
          </div>
        </div>
        
        <!-- Footer -->
        <div style="background: #2d3748; color: white; padding: 25px; text-align: center;">
          <p style="margin: 0 0 10px 0; font-size: 14px;">
            This is an automated security alert from IncomeGrow Financial Security System
          </p>
          <p style="margin: 0 0 15px 0; font-size: 13px; color: #a0aec0;">
            Alert ID: {{alertId}} | Generated: {{timestamp}}
          </p>
          <p style="margin: 0; font-size: 12px; color: #718096;">
            © 2024 IncomeGrow Financial | Your Security is Our Priority
          </p>
        </div>
      </div>
    `,
    textContent: 'SECURITY ALERT: {{alertType}} detected on your account, {{userName}}. Incident: {{alertDescription}} at {{incidentTime}} from {{location}} ({{deviceInfo}}, {{ipAddress}}). If this was you, confirm: {{confirmUrl}}. If NOT you, secure account: {{secureAccountUrl}} or call {{emergencyPhone}}. Alert ID: {{alertId}}',
    variables: ['userName', 'alertType', 'alertDescription', 'incidentTime', 'location', 'deviceInfo', 'ipAddress', 'confirmUrl', 'secureAccountUrl', 'emergencyPhone', 'alertId', 'timestamp'],
    category: 'notification',
  },
  {
    name: 'Goal Achievement Celebration',
    subject: '🎉 Congratulations! You achieved your {{goalName}} goal!',
    htmlContent: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff;">
        <!-- Celebration Header -->
        <div style="background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%); padding: 40px 20px; text-align: center; position: relative; overflow: hidden;">
          <div style="position: absolute; top: -20px; left: 20px; font-size: 60px; opacity: 0.3; transform: rotate(-15deg);">🎉</div>
          <div style="position: absolute; top: 30px; right: 30px; font-size: 40px; opacity: 0.4; transform: rotate(15deg);">🏆</div>
          <div style="position: absolute; bottom: 20px; left: 40px; font-size: 30px; opacity: 0.3;">✨</div>
          <div style="position: absolute; bottom: 40px; right: 20px; font-size: 35px; opacity: 0.4;">🌟</div>
          
          <div style="position: relative; z-index: 2;">
            <h1 style="color: #e85a4f; margin: 0 0 10px 0; font-size: 36px; font-weight: 800; text-shadow: 2px 2px 4px rgba(0,0,0,0.1);">🎉 GOAL ACHIEVED! 🎉</h1>
            <p style="color: #c73650; margin: 0; font-size: 18px; font-weight: 600;">Congratulations on your financial milestone!</p>
          </div>
        </div>
        
        <!-- Achievement Details -->
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; text-align: center; color: white;">
          <div style="background: rgba(255,255,255,0.15); border-radius: 20px; padding: 30px; backdrop-filter: blur(10px);">
            <h2 style="margin: 0 0 15px 0; font-size: 28px; font-weight: 300; text-shadow: 0 2px 4px rgba(0,0,0,0.2);">{{goalName}}</h2>
            <div style="margin: 25px 0;">
              <div style="font-size: 18px; opacity: 0.9; margin-bottom: 10px;">Target Amount</div>
              <div style="font-size: 48px; font-weight: 700; text-shadow: 0 2px 6px rgba(0,0,0,0.3);">{{targetAmount}}</div>
            </div>
            <div style="background: rgba(255,255,255,0.2); padding: 15px; border-radius: 10px; margin-top: 20px;">
              <div style="font-size: 16px; margin-bottom: 5px;">Achieved in</div>
              <div style="font-size: 24px; font-weight: bold;">{{timeToAchieve}}</div>
            </div>
          </div>
        </div>
        
        <!-- Journey Stats -->}
        <div style="padding: 40px 30px; background: #f8f9ff;">
          <h3 style="color: #333; margin: 0 0 30px 0; font-size: 24px; font-weight: 600; text-align: center;">Your Achievement Journey</h3>
          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 20px;">
            <div style="background: linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%); padding: 25px; border-radius: 15px; text-align: center; color: white; box-shadow: 0 4px 15px rgba(132, 250, 176, 0.3);">
              <div style="font-size: 32px; font-weight: bold; margin-bottom: 5px;">{{monthsInvested}}</div>
              <div style="font-size: 14px; opacity: 0.9;">Months Invested</div>
            </div>
            <div style="background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%); padding: 25px; border-radius: 15px; text-align: center; color: #333; box-shadow: 0 4px 15px rgba(168, 237, 234, 0.3);">
              <div style="font-size: 32px; font-weight: bold; margin-bottom: 5px;">{{totalContributions}}</div>
              <div style="font-size: 14px; opacity: 0.8;">Total Contributed</div>
            </div>
            <div style="background: linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%); padding: 25px; border-radius: 15px; text-align: center; color: #333; box-shadow: 0 4px 15px rgba(251, 194, 235, 0.3);">
              <div style="font-size: 32px; font-weight: bold; margin-bottom: 5px; color: #28a745;">{{totalGrowth}}</div>
              <div style="font-size: 14px; opacity: 0.8;">Investment Growth</div>
            </div>
          </div>
        </div>
        
        <!-- Personal Message -->
        <div style="padding: 40px 30px; background: white;">
          <div style="background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%); padding: 30px; border-radius: 15px; text-align: center;">
            <h3 style="color: #d73502; margin: 0 0 20px 0; font-size: 24px; font-weight: 600;">
              🌟 Personal Message from Your Advisor
            </h3>
            <div style="background: rgba(255,255,255,0.8); padding: 25px; border-radius: 12px;">
              <p style="color: #333; line-height: 1.7; margin: 0 0 15px 0; font-size: 16px; font-style: italic;">
                "{{personalMessage}}"
              </p>
              <p style="color: #666; margin: 0; font-size: 14px; font-weight: 600;">
                - {{advisorName}}, Your Financial Advisor
              </p>
            </div>
          </div>
        </div>
        
        <!-- Next Steps -->
        <div style="padding: 40px 30px; background: #f0f8ff;">
          <h3 style="color: #333; margin: 0 0 25px 0; font-size: 22px; font-weight: 600; text-align: center;">🚀 What's Next?</h3>
          <div style="display: grid; gap: 20px;">
            <div style="background: white; padding: 25px; border-radius: 12px; display: flex; align-items: center; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">
              <div style="background: #4CAF50; color: white; width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 20px; flex-shrink: 0; font-size: 20px;">🎯</div>
              <div>
                <h4 style="color: #333; margin: 0 0 8px 0; font-size: 16px; font-weight: 600;">Set Your Next Goal</h4>
                <p style="color: #666; margin: 0; font-size: 14px; line-height: 1.5;">Continue building wealth with a new financial target</p>
              </div>
            </div>
            <div style="background: white; padding: 25px; border-radius: 12px; display: flex; align-items: center; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">
              <div style="background: #2196F3; color: white; width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 20px; flex-shrink: 0; font-size: 20px;">📊</div>
              <div>
                <h4 style="color: #333; margin: 0 0 8px 0; font-size: 16px; font-weight: 600;">Optimize Your Portfolio</h4>
                <p style="color: #666; margin: 0; font-size: 14px; line-height: 1.5;">Let's review and enhance your investment strategy</p>
              </div>
            </div>
            <div style="background: white; padding: 25px; border-radius: 12px; display: flex; align-items: center; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">
              <div style="background: #FF6B2C; color: white; width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 20px; flex-shrink: 0; font-size: 20px;">🏠</div>
              <div>
                <h4 style="color: #333; margin: 0 0 8px 0; font-size: 16px; font-weight: 600;">Explore New Opportunities</h4>
                <p style="color: #666; margin: 0; font-size: 14px; line-height: 1.5;">Discover investment options that align with your success</p>
              </div>
            </div>
          </div>
        </div>
        
        <!-- CTA -->
        <div style="padding: 40px 30px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); text-align: center;">
          <h3 style="color: white; margin: 0 0 20px 0; font-size: 22px; font-weight: 600;">Ready for Your Next Financial Goal?</h3>
          <a href="{{setNewGoalUrl}}" style="background: #FF6B2C; color: white; padding: 18px 40px; text-decoration: none; border-radius: 30px; font-weight: bold; font-size: 18px; display: inline-block; margin-right: 15px; box-shadow: 0 6px 20px rgba(255, 107, 44, 0.4);">
            Set New Goal 🎯
          </a>
          <a href="{{scheduleCallUrl}}" style="background: transparent; color: white; padding: 18px 40px; text-decoration: none; border: 2px solid white; border-radius: 30px; font-weight: bold; font-size: 18px; display: inline-block;">
            Schedule Call 📞
          </a>
        </div>
        
        <!-- Footer -->
        <div style="background: #2c3e50; color: white; padding: 30px; text-align: center;">
          <p style="margin: 0 0 15px 0; font-size: 16px; font-weight: 600;">
            🎉 Share your achievement with friends and family!
          </p>
          <div style="margin-bottom: 20px;">
            <a href="{{shareTwitterUrl}}" style="background: #1da1f2; color: white; padding: 8px 15px; text-decoration: none; border-radius: 5px; margin: 0 5px; font-size: 12px;">Share on Twitter</a>
            <a href="{{shareLinkedInUrl}}" style="background: #0077b5; color: white; padding: 8px 15px; text-decoration: none; border-radius: 5px; margin: 0 5px; font-size: 12px;">Share on LinkedIn</a>
          </div>
          <p style="margin: 0; font-size: 12px; color: #95a5a6;">© 2024 IncomeGrow Financial | Celebrating Your Financial Success</p>
        </div>
      </div>
    `,
    textContent: 'GOAL ACHIEVED! Congratulations {{userName}}! You reached your {{goalName}} goal of {{targetAmount}} in {{timeToAchieve}}. Journey: {{monthsInvested}} months, {{totalContributions}} contributed, {{totalGrowth}} growth. Message from {{advisorName}}: "{{personalMessage}}". Set your next goal: {{setNewGoalUrl}}',
    variables: ['userName', 'goalName', 'targetAmount', 'timeToAchieve', 'monthsInvested', 'totalContributions', 'totalGrowth', 'personalMessage', 'advisorName', 'setNewGoalUrl', 'scheduleCallUrl', 'shareTwitterUrl', 'shareLinkedInUrl'],
    category: 'announcement',
  }
];

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    await dbConnect();

    // Find an admin user to assign as creator
    const adminUser = await User.findOne({ role: 'admin' });
    if (!adminUser) {
      return res.status(400).json({ error: 'No admin user found' });
    }

    const createdTemplates = [];

    for (const templateData of premiumTemplates) {
      // Check if template already exists
      const existingTemplate = await EmailTemplate.findOne({ 
        name: templateData.name 
      });

      if (!existingTemplate) {
        const template = new EmailTemplate({
          ...templateData,
          createdBy: adminUser._id,
        });

        await template.save();
        createdTemplates.push(template.name);
      }
    }

    res.status(200).json({
      message: `Created ${createdTemplates.length} premium email templates`,
      createdTemplates,
    });
  } catch (error: any) {
    console.error('Create premium templates error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}